### ISSUE TITLE
Dropping old CUDA `skip`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/stir-feedstock#114]
CUDA 10.2 has already been dropped in conda-forge. So it should be safe to drop this

https://github.com/conda-forge/stir-feedstock/blob/b7f5a8f5ee2121cdf17ffe492572e37c8718080f/recipe/meta.yaml#L19

Also `cudatoolkit` only applies on CUDA 11. So this could have a selector to limit to CUDA 11

https://github.com/conda-forge/stir-feedstock/blob/b7f5a8f5ee2121cdf17ffe492572e37c8718080f/recipe/meta.yaml#L20-L21

Lastly it may be worthwhile to add a `cuda-version` dependency in `host` & `run` to align packages with a specific CUDA version for installing

```yaml
host:
    ...
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
  run:
    ...
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
```
