### ISSUE TITLE
ITK version mismatch

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/stir-feedstock#34]
I installed STIR with Miniconda on Windows 10 but could not use any of the utilities nor python, with problems on DLLs.

Checking with dumpbin (or https://github.com/lucasg/Dependencies ), I find that the DLL _stir.pyd needs ITK 5.1 libraries, while the environment installed ITK 5.2 libraries.

I had to do the following to fix this (using Powershell for the 3rd line)
```
conda create -n stir-python3.8 python=3.8  stir  matplotlib libitk=5.1
conda activate stir-python3.8
```
where I got the directory name from "conda env list" and I had to fix Python to 3.8 as libitk isn't distributed for 3.9

Is there a mistake in our conda recipe? Should it specify versions of dependencies? That'd be dreadful.

**Comment by carterbox** [comment]
I checked the latest package build on anaconda.org. It seems that the de-templated recipe is correct. It is de-templated to the following:

```yaml
# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 30 23:07:23 2022
# ------------------------------------------------

package:
  name: stir
  version: 5.0.2
source:
  git_rev: rel_5.0.2
  git_url: https://github.com/UCL/STIR.git
build:
  number: '5'
  string: py310h6a7e225_5
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
# Lines omitted for brevity 
  host:
# Lines omitted for brevity 
    - libgomp 12.2.0 h65d4601_19
    - libiconv 1.17 h166bdaf_0
    - libitk 5.2.1 hcedbc38_6
    - libitk-devel 5.2.1 h0a2745d_6
    - liblapack 3.9.0 16_linux64_openblas
    - libllvm9 9.0.1 default_hc23dcda_7
  run:
    - _openmp_mutex >=4.5
    - hdf5 >=1.12,<1.13.0a0
    - hdf5 >=1.12.2,<1.12.3.0a0
    - libgcc-ng >=12
    - libgomp
    - libitk >=5.2,<5.3.0a0
    - libstdcxx-ng >=12
    - numpy >=1.21.6,<2.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - root_base >=6.26,<6.27.0a0
    - root_base >=6.26.8,<6.26.9.0a0
# Trimmed for brevity
```
As is desired, a package built against `5.2.1` is required to run with `libitk >=5.2,<5.3.0a0`.

I don't think the error is with this recipe. If the problem is intermittent, then I suspect a bug in the environment solver.

The only thing I would change is dropping the `min_pin='x.x'` because it by default, the pinning template uses a stricter 'min_pin='x.x.x', but this is most likely unrelated to this problem.
